#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_topmost off
yabai -m config window_opacity on
yabai -m config window_border off
yabai -m config window_shadow on
yabai -m config window_border_width 6
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config normal_window_border_color 0xff000000
yabai -m config active_window_border_color 0xff646962
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

yabai -m config layout bsp

yabai -m config top_padding 12
yabai -m config bottom_padding 56
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

yabai -m config active_window_opacity 1
yabai -m config normal_window_opacity 1
yabai -m config normal_opacity_duration 0.0
# yabai -m config window_resize_step            25
#
# yabai -m config window_min_width 50
# yabai -m config window_min_height 50

# default layout (can be bsp, stack or float)
# general space settings

# padding set to 12px
# New window spawns to the right if vertical split, or bottom if horizontal split
# yabai -m config window_placement second_child

# modifier for clicking and dragging with mouse
#yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
# yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
# yabai -m config mouse_action2 resize

# yabai -m config window_resize_step 20

# when window is dropped in center of another window, swap them (on edges it will split it)
# yabai -m mouse_drop_action swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
# yabai -m rule --add app="Finder" title=" Info" manage=off
# yabai -m rule --add app="Finder" title="Copy" manage=off
# yabai -m rule --add app="Finder" title="Mov" manage=off
# yabai -m rule --add app="Finder" title="Trash" manage=off
# yabai -m rule --add title="Preferences" manage=off
# yabai -m rule --add app="iTunes" title="MiniPlayer" manage=off
# yabai -m rule --add app="Music" title="MiniPlayer" manage=off
# yabai -m rule --add app="Front" title="New Message" manage=off
# yabai -m rule --add app="Front" title="New Discussion" manage=off
# yabai -m rule --add app="Firefox" title="Picture-in-Picture" manage=off
# yabai -m rule --add app="Google Chrome" title="Picture in Picture" manage=off
# yabai -m rule --add app="VLC"
# yabai -m rule --add app="Transmit" title="Activity" manage=off yabai -m rule --add app="^Karabiner-Elements$" manage=off
